import { formatNumber, formatUsd, type MetricsResult } from "@/lib/metrics";

interface ReportInput {
  systemPrompt: string;
  userPrompt: string;
  outputTokens: number;
  callsPerMonth: number;
  results: (MetricsResult & {
    monthlyCost: number;
    monthlyCo2: number;
    monthlyWater: number;
  })[];
}

/**
 * Build a printable HTML report and trigger the browser print dialog so the
 * user can "Save as PDF". Avoids bundling a PDF library to keep the app fast.
 */
export function downloadReport(input: ReportInput) {
  const { systemPrompt, userPrompt, outputTokens, callsPerMonth, results } = input;

  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) return;

  const rows = results
    .map(
      (r) => `
      <tr>
        <td><strong>${escapeHtml(r.model.displayName)}</strong><br/><span class="muted">${escapeHtml(r.model.provider)}</span></td>
        <td class="num">${r.inputTokens.toLocaleString()}</td>
        <td class="num">${r.outputTokens.toLocaleString()}</td>
        <td class="num">${formatUsd(r.costUsd)}</td>
        <td class="num">${formatUsd(r.monthlyCost)}</td>
        <td class="num">${formatNumber(r.facilityEnergyWh, 3)}</td>
        <td class="num">${formatNumber(r.waterMl, 2)}</td>
        <td class="num">${formatNumber(r.co2eG, 3)}</td>
        <td class="num">${r.ttftMs} ms</td>
        <td class="num">${formatNumber(r.e2eLatencyMs, 0)} ms</td>
      </tr>`,
    )
    .join("");

  const html = `
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>TokenMetrics report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0f172a; margin: 32px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 24px 0 8px; color: #334155; }
  p, td, th { font-size: 12px; }
  .muted { color: #64748b; font-size: 11px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; }
  th, td { border-bottom: 1px solid #e2e8f0; padding: 8px 6px; text-align: left; }
  th { background: #f8fafc; font-weight: 600; text-transform: uppercase; font-size: 10px; letter-spacing: 0.04em; color: #475569; }
  .num { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; text-align: right; }
  pre { background: #f8fafc; padding: 10px; border-radius: 6px; white-space: pre-wrap; font-size: 11px; max-height: 200px; overflow: hidden; }
  .meta { color: #64748b; font-size: 11px; }
</style>
</head>
<body>
  <h1>TokenMetrics report</h1>
  <div class="meta">Generated ${new Date().toLocaleString()} · Expected output ${outputTokens} tokens · ${callsPerMonth.toLocaleString()} calls/month</div>

  <h2>Prompt</h2>
  <pre>${escapeHtml((systemPrompt + "\n\n" + userPrompt).trim() || "(empty)")}</pre>

  <h2>Metrics by model</h2>
  <table>
    <thead>
      <tr>
        <th>Model</th><th>Input</th><th>Output</th>
        <th>Cost/call</th><th>Monthly</th>
        <th>Energy (Wh)</th><th>Water (mL)</th><th>CO₂e (g)</th>
        <th>TTFT</th><th>E2E</th>
      </tr>
    </thead>
    <tbody>${rows || `<tr><td colspan="10" class="muted">No data.</td></tr>`}</tbody>
  </table>

  <p class="meta">Methodology: cost = (tokens/1M)·price. Energy follows Jegham et al. (2025) per-token estimates × PUE 1.3. Water uses combined on-site + electricity WUE for U.S. datacenter averages.</p>
  <p class="meta">Generated by TokenMetrics.ai · We never store or train on your prompts.</p>

  <script>window.onload = () => setTimeout(() => window.print(), 250);</script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}