import { formatNumber, formatUsd, type MetricsResult } from "@/lib/metrics";

interface ReportInput {
  systemPrompt: string;
  userPrompt: string;
  outputTokens: number;
  callsPerMonth: number;
  results: (MetricsResult & {
    monthlyCost: number;
    monthlyCo2: number;
    monthlyWater: number;
    facts: { costFact: string; waterFact: string };
  })[];
}

/**
 * Build a printable HTML report and trigger the browser print dialog so the
 * user can "Save as PDF". Avoids bundling a PDF library to keep the app fast.
 */
export function downloadReport(input: ReportInput) {
  const { systemPrompt, userPrompt, outputTokens, callsPerMonth, results } = input;

  const win = window.open("", "_blank", "width=900,height=1100");
  if (!win) return;

  const rows = results
    .map(
      (r) => `
      <tr>
        <td><strong>${escapeHtml(r.model.displayName)}</strong><br/><span class="muted">${escapeHtml(r.model.provider)}</span></td>
        <td class="num">${r.inputTokens.toLocaleString()}</td>
        <td class="num">${r.outputTokens.toLocaleString()}</td>
        <td class="num">${formatUsd(r.costUsd)}</td>
        <td class="num">${formatUsd(r.monthlyCost)}</td>
        <td class="num">${formatNumber(r.facilityEnergyWh, 3)}</td>
        <td class="num">${formatNumber(r.waterMl, 1)}</td>
        <td class="num">${formatNumber(r.co2eG, 3)}</td>
        <td class="num">${r.ttftMs} ms</td>
        <td class="num">${formatNumber(r.e2eLatencyMs, 0)} ms</td>
      </tr>`,
    )
    .join("");

  const factsSections = results
    .map(
      (r) => `
      <div class="model-fact-card">
        <h3>${escapeHtml(r.model.displayName)} (${escapeHtml(r.model.provider)})</h3>
        <p><strong>Cost impact (${formatUsd(r.monthlyCost)}/mo):</strong> ${escapeHtml(r.facts.costFact)}</p>
        <p><strong>Water footprint (${formatNumber(r.monthlyWater / 1000, 1)} L/mo):</strong> ${escapeHtml(r.facts.waterFact)}</p>
      </div>`,
    )
    .join("");

  const html = `
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>TokenMetrics report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0f172a; margin: 32px; }
  h1 { font-size: 20px; margin: 0 0 4px; }
  h2 { font-size: 14px; margin: 24px 0 8px; color: #334155; border-bottom: 2px solid #f1f5f9; padding-bottom: 4px; }
  p, td, th { font-size: 12px; }
  .muted { color: #64748b; font-size: 11px; }
  table { width: 100%; border-collapse: collapse; margin-top: 8px; margin-bottom: 20px; }
  th, td { border-bottom: 1px solid #e2e8f0; padding: 8px 6px; text-align: left; }
  th { background: #f8fafc; font-weight: 600; text-transform: uppercase; font-size: 10px; letter-spacing: 0.04em; color: #475569; }
  .num { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; text-align: right; }
  pre { background: #f8fafc; padding: 10px; border-radius: 6px; white-space: pre-wrap; font-size: 11px; max-height: 150px; overflow: hidden; border: 1px solid #e2e8f0; }
  .meta { color: #64748b; font-size: 11px; }
  .model-fact-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 10px 14px; margin-bottom: 10px; background: #f8fafc; }
  .model-fact-card h3 { font-size: 12px; margin: 0 0 6px; color: #0f172a; font-weight: 600; }
  .model-fact-card p { font-size: 11px; margin: 4px 0; color: #475569; line-height: 1.4; }
  .facts-grid { display: grid; grid-template-columns: 1fr; gap: 8px; margin-top: 10px; }
</style>
</head>
<body>
  <h1>TokenMetrics Evaluation Report</h1>
  <div class="meta">Generated ${new Date().toLocaleString()} · Expected output ${outputTokens} tokens · ${callsPerMonth.toLocaleString()} calls/month</div>

  <h2>Prompt context</h2>
  <pre>${escapeHtml((systemPrompt + "\n\n" + userPrompt).trim() || "(empty)")}</pre>

  <h2>Metrics by model</h2>
  <table>
    <thead>
      <tr>
        <th>Model</th><th>Input</th><th>Output</th>
        <th>Cost/call</th><th>Monthly</th>
        <th>Energy (Wh)</th><th>Water (mL)</th><th>CO₂e (g)</th>
        <th>TTFT</th><th>E2E</th>
      </tr>
    </thead>
    <tbody>${rows || `<tr><td colspan="10" class="muted">No data.</td></tr>`}</tbody>
  </table>

  <h2>Real-world relatable impacts</h2>
  <div class="facts-grid">${factsSections || `<p class="muted">No model comparison data.</p>`}</div>

  <p class="meta" style="margin-top: 30px;">Methodology: Cost = (tokens/1M)·price. Energy follows Jegham et al. (2025) per-token estimates × PUE 1.3. Water footprint model accounts for Scope 1 (cooling) and Scope 2 (grid generation) WUE factors (Li et al. 2023).</p>
  <p class="meta">Generated by EcoMetrics.ai · Local-first browser benchmarking.</p>

  <script>window.onload = () => setTimeout(() => window.print(), 350);</script>
</body>
</html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
}
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
