/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CarbonTrackerRouteImport } from './routes/carbon-tracker'
import { Route as IndexRouteImport } from './routes/index'

const CarbonTrackerRoute = CarbonTrackerRouteImport.update({
  id: '/carbon-tracker',
  path: '/carbon-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carbon-tracker': typeof CarbonTrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carbon-tracker': typeof CarbonTrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carbon-tracker': typeof CarbonTrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carbon-tracker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carbon-tracker'
  id: '__root__' | '/' | '/carbon-tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarbonTrackerRoute: typeof CarbonTrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/carbon-tracker': {
      id: '/carbon-tracker'
      path: '/carbon-tracker'
      fullPath: '/carbon-tracker'
      preLoaderRoute: typeof CarbonTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarbonTrackerRoute: CarbonTrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
